# Generated by Django 4.0.4 on 2023-08-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='dates',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='price_close',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='price_high',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='price_low',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='price_open',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='volume',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
    ]
