# Generated by Django 4.0.4 on 2023-08-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ticker_dates_ticker_price_close_ticker_price_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='dates',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price_close',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price_high',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price_low',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price_open',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
