# Generated by Django 4.0.4 on 2023-08-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_ticker_ticker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='dates',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price_close',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price_high',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price_low',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price_open',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='ticker_name',
            field=models.JSONField(),
        ),
    ]
