# Generated by Django 4.0.4 on 2023-08-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_ticker_dates_alter_ticker_price_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='dates',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price_close',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price_high',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price_low',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price_open',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='ticker_name',
            field=models.TextField(null=True),
        ),
    ]
