# Generated by Django 4.0.4 on 2023-08-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_ticker_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='average_close',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='average_open',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='max_close',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='min_open',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
